### ISSUE TITLE
Citation

### ISSUE THREAD

**Issue by Kaleidophon** [UniversalDependencies/UD_Finnish-OOD#1]
Hey, I am planning to use your data for my work. How would you like your data to be cited?

**Comment by jmnybl** [comment]
Unfortunately we do not have a paper published yet, so general UD citation + URL to the repository is likely the best option. I'll update the citation information then when we have one. Thank you for asking!

**Comment by Kaleidophon** [comment]
Thanks! I will do so

**Comment by jmnybl** [comment]
The paper is now accepted for publication, the correct citation is:

```
@inproceedings{kanerva-2022-ood,
    title = "Out-of-Domain Evaluation of Finnish Dependency Parsing",
    author = {Kanerva, Jenna and Ginter, Filip},
    booktitle = "Proceedings of the 13th International Conference on Language Resources and Evaluation (LREC'22)",
    year = "2022"
}
```

**Comment by Kaleidophon** [comment]
Perfect, thank you so much!
