### ISSUE TITLE
Better representation of this misc field?

### ISSUE THREAD

**Issue by AngledLuffa** [UniversalDependencies/UD_Finnish-OOD#2]
https://github.com/UniversalDependencies/UD_Finnish-OOD/blob/e8f835abcc4f587c23dd991c7d828e292ac06bfa/fi_ood-ud-test.conllu#L5470

This is technically allowed by the UD guidelines

https://universaldependencies.org/misc.html#basic-format

However, since the | is not representative of anything in the text, is there a better separator to use here or a label that could go on the second half of this misc annotation?

**Comment by AngledLuffa** [comment]
Elsewhere in this treebank, there are misc annotations such as

`Gen_desc=verenkiertojärjestelmän_toiminta|Gen=Verenkiertojärjestelmä`

Perhaps that style (with the extra `Gen=`) was the intent here?

**Comment by jmnybl** [comment]
Thanks, this is now fixed in the dev branch.
